### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by JoergStrebel** [frank-zago/xgalaga-sdl#3]
Hallo!
I really like this game and would like to contribute to its development. I have some ideas in mind:
- finish the SDL2 port and remove SDL1.x
- Fix the defect with the highscore list - the game crashes when I enter my name and it does not save my entries.
- Add installation of packages required to build it on openSUSE Leap 15.2

What do you think? Is this project still active?
Thank you!
J. Strebel

**Comment by frank-zago** [comment]
I'd say that project is in long term maintenance. It is done, but patches are welcome.

I though the SDL2 port was finished. What's missing? As for removing SDL1 support, I don't know; is it in the way?

I've not seen a crash with the highscore list. Feel free to submit a patch.

**Comment by JoergStrebel** [comment]
Ok, I see - so you are interested only in bugfixing. That's ok - I'll fork the project and build my own version. 
The current SDL version is 2.0.14, I don't see why SDL V1 is still needed. Removing SDL1 will also make the source code simpler and better readable. But I understand that this is no concern of yours.
