### ISSUE TITLE
Non-ASCII characters in user name lead to program crash

### ISSUE THREAD

**Issue by JoergStrebel** [frank-zago/xgalaga-sdl#6]
If getpwuid(getuid()) returns a name with Non-ASCII characters , the game will crash as soon as the player is supposed to enter his name in the highscore list.

**Comment by frank-zago** [comment]
I merged the PR. The real fix is more work than I'd like to put in. Probably remove the old fixed size fonts and change the text input out to fully use sdl. I suspect entering non-ascii characters in new highscore could also be bad somewhere.
